version: '3'

volumes:
  test_project_local_postgres_data: {}
  test_project_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: test_project_local_django
    container_name: test_project_local_django
    platform: linux/x86_64
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - .env.dev
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: test_project_production_postgres
    container_name: test_project_local_postgres
    volumes:
      - test_project_local_postgres_data:/var/lib/postgresql/data:Z
      - test_project_local_postgres_data_backups:/backups:z
    env_file:
      - .env.dev

  redis:
    image: redis:6
    container_name: test_project_local_redis

  celeryworker:
    <<: *django
    image: test_project_local_celeryworker
    container_name: test_project_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: test_project_local_celerybeat
    container_name: test_project_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: test_project_local_flower
    container_name: test_project_local_flower
    ports:
      - "5555:5555"
    command: /start-flower




